name: D CI with dub

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - name: Build
        run: dub build
      - name: Test
        run: dub test
